[package]
name = "wasm_sample"
version = "0.1.0"

[dependencies]
wasm-bindgen = "0.2.45"

[dependencies.web-sys]
version = "0.3.63"
features = [
"HtmlCanvasElement",
"CanvasRenderingContext2d",
"Window",
"Document"
]

[lib]
crate-type =["cdylib"]
